apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: oci-bv
        resources:
          requests:
            storage: 5Gi
