apiVersion: v1
kind: Secret
metadata:
  name: homepage-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongo:27017"
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  JWT_SECRET: "change-me-to-a-long-random-string"
  SESSION_COOKIE: "homepage_session"
